format = """
[░▒▓](#d73737)\
$os\
$username$hostname\
[](bg:#a30000 fg:#d73737)\
$directory\
[](fg:#a30000)
$git_branch\
$git_status\
[](fg:#720000 bg:#390000)\
$nodejs\
$python\
[](fg:#390000)\
\n$character"""

[username]
show_always = true
format = '[ $user](bg:#d73737 fg:#090c0c bold)'
disabled = false

[hostname]
ssh_only = false
format = '[@$hostname](bg:#d73737 fg:#090c0c bold)'

[directory]
style = "fg:#FFFFFF bg:#a30000 bold"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = false

[git_commit]
format = '[\($hash\)](yellow)[$tag](blue bold) '
tag_disabled = false
only_detached = false
tag_symbol = ' 󱩺 '

[git_branch]
format = '[ $symbol](fg:#eeebef bg:#720000)[$branch(:$remote_branch)](fg:#eeebef bg:#720000)'

[git_status]
format = '([ \[$all_status$ahead_behind\]](fg:#b0dc4c bg:#720000 bold))'

[python]
format = '[ $symbol${pyenv_prefix}(${version}) (\($virtualenv\) )](fg:#FFFFFF bg:#390000)'
symbol = '󰌠 '

[nodejs]
format = '[ $symbol$version ](fg:#FFFFFF bg:#390000)'

[os]
format = "[$symbol](bg:#d73737 fg:#090c0c bold)"
disabled = false

[os.symbols]
Macos = "  "
Mint = " 󰌪 "
